version: "3"
services:
  db_sales:
    build: ./database/
    container_name: db_sales
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./database/.env.docker
    volumes:
      - pg:/var/lib/postgresql/data
      - ./database/excels/metas.csv:/usr/metas.csv
      - ./database/excels/venda_produtos.csv:/usr/venda_produtos.csv
      - ./database/excels/vendas.csv:/usr/vendas.csv

  fastify_backend:
    container_name: fastify_backend
    build: ./backend/
    ports:
      - 5000:5000
    depends_on:
      - db_sales
    env_file:
      - ./backend/.env.docker

  vue_frontend:
    build: ./frontend
    container_name: vue_frontend
    volumes:
      - frontend:/home/app
    ports:
      - '8080:8080'

volumes:
  pg:
  frontend:
